version: '3.1'
services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "6969:6969"
    volumes:
      - ./app:/usr/src/app/dev-games-mvp
      - /usr/src/app/dev-games-mvp/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
